# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae39add63250e96e751fa077c28cc8cc48937cd424578e828040051fe2806a971959c50d90b07b2dc5842594e3f9e10261a21922e67d5f4a49f927dd4eb86a6c

test:
  secret_key_base: 21d0de8dc113bca905e7eaab1b463d6cde0895624c6478073deeb223e498ef8221918f75ed481d91cb1306b9a4c9668744609d7deeec3c74747060abed2f7b7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
